In [8]:
import pandas as pd

In [9]:
df = pd.read_csv(r"C:\Users\Anooj Dilip Archana\Downloads\evapotranspiration_crop_prediction_dataset.csv")

In [10]:
df

,Crop Type,Temperature (°C),Humidity (%),Wind Speed (m/s),Solar Radiation (MJ/m²),Rainfall (mm),Soil Type,Soil Moisture (%),Irrigation (mm/day),"Evapotranspiration (ET, mm/day)"
0,Maize,19.628323,73.635150,2.271360,12.504393,18.271560,Loam,45.759507,12.557713,2.797641
1,Sugarcane,28.547524,79.834070,2.630460,14.428043,10.507210,Sandy,48.643883,21.191626,3.940382
2,Wheat,36.823646,52.523395,4.345463,22.806195,14.498205,Sandy,45.404199,24.172171,8.490188
3,Maize,33.305622,71.243705,2.030020,21.967989,8.720966,Clay,10.328028,12.403267,7.366348
4,Maize,35.164029,68.587299,4.413424,16.558355,12.600692,Loam,35.658434,21.823881,5.543607
...,...,...,...,...,...,...,...,...,...,...
1995,Wheat,36.632394,84.869866,3.108817,18.694083,7.188901,Sandy,10.787572,18.002835,6.032290
1996,Rice,18.931830,45.969051,3.501666,14.149816,18.534150,Clay,37.615103,11.439662,4.110502
1997,Wheat,22.744696,56.392142,4.602096,24.710267,13.973140,Sandy,47.380729,5.821986,8.511390
1998,Maize,22.251138,80.787269,2.055291,13.403019,5.143543,Loam,38.557683,14.913288,3.130772
1999,Wheat,36.785351,69.865619,3.296783,24.115274,11.281698,Loam,11.471749,5.256367,8.570665

In [11]:
df.describe()

,Temperature (°C),Humidity (%),Wind Speed (m/s),Solar Radiation (MJ/m²),Rainfall (mm),Soil Moisture (%),Irrigation (mm/day),"Evapotranspiration (ET, mm/day)"
count,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000
mean,27.617788,64.612009,2.731490,18.297638,10.024867,29.962417,15.046887,5.787234
std,7.284231,14.329203,1.302315,3.685685,5.685499,11.435049,5.711168,1.586624
min,15.000291,40.001536,0.506428,12.003133,0.001057,10.004746,5.003510,2.387510
25%,21.346349,52.113540,1.600206,15.144530,5.133748,20.092344,10.221744,4.487323
50%,27.728909,64.377492,2.687829,18.264909,10.021671,30.280458,14.933097,5.753042
75%,33.990529,76.896678,3.881827,21.294251,14.933997,39.514146,19.769059,7.030562
max,39.985343,89.977885,4.997573,24.985761,19.993464,49.992669,24.997853,9.528008

In [12]:
df.shape

(2000, 10)